# Generated by Django 4.0.5 on 2022-07-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clase19', '0004_curso_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='emial',
            new_name='email',
        ),
    ]
